version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=shuharib0t
      - POSTGRES_PASSWORD=Fm7qt4Qg5u2gcU5Nf7nRlg7eLJhsaIC8
      - POSTGRES_DB=polls_udau
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "polls_redis_data:/bitnami/redis/data"

volumes:
  polls_pg_data:
  polls_redis_data:
